### ISSUE TITLE
setting notmuch path to /usr/bin/notmuch

### ISSUE THREAD

**Issue by WillForan** [inbasic/notmuch-email-client#1]
I see there is a path setting "notmuch" in https://github.com/inbasic/notmuch-email-client/blob/master/native/base.js#L5. but am not sure where to set it in the json plugin preferences (firefox). The "one last step" page has some hints
> ... path is not correct in the options page

but setting neither "path" nor "notmuch" keys resolve the side bar error message:

> Error: {"code":-1,"type":"exception","error":"Error: spawn /usr/local/bin/notmuch ENOENT\n at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)\n at onErrorNT (internal/child_process.js:407:16)\n at process._tickCallback (internal/process/next_tick.js:63:19)"}

**Comment by inbasic** [comment]
Since there is no place yet, open the background page and run `localStorage.setItem('notmuch', 'path-to-the-executable')`. You can access the background page from about:debugging.

I'll add the UI to insert this preference in the error page. btw, what is your notmuch path?

**Comment by WillForan** [comment]
That did the trick. `/usr/bin/notmuch` for me, but just `notmuch` seems to work too. I had to restart firefox to see the change.
Thanks for the quick response!
